### PR TITLE
Update by-laws.md

### PR DESCRIPTION
**Pull request by balghane**
I set up a redirect on my personal webpage, so that I can link to the latest bylaws without updating Github every time

### CODE REVIEW

**Comment by nickbabcock** [comment]
I'm not in favor of this. No one will know when the by-laws change and we'd be relying on you to remain a student forever and manually update your link whenever the by-laws change.

**Comment by clharman** [comment]
It's not necessary.  On google drive, use "manage versions" -> "upload new version".  This solves the problem as the new version will be linked automatically.

**Comment by balghane** [comment]
Oh, I didn't realise that was a thing that existed

**Comment by nickbabcock** [comment]
No worries, thanks for looking out for the website :+1:

**Pull request closed without merging**
